language: objective-c
osx_image: xcode7.2

cache:
  directories:
  - vendor/bundle
  - ./Carthage

notifications:
  email: false

before_install:
    - brew update
    - brew upgrade carthage || brew install carthage
install:
    - bundle install --without development --deployment --jobs=3 --retry=3
    - tools/carthage_cache_ci.sh

script:
    - bundle exec fastlane test
